chore(deps): bump go.temporal.io/api from 1.55.0 to 1.57.0 in the temporal group across 1 directory (#753)
Bumps the temporal group with 1 update in the / directory:
[go.temporal.io/api](https://github.com/temporalio/api-go).

Updates `go.temporal.io/api` from 1.55.0 to 1.57.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/temporalio/api-go/releases">go.temporal.io/api's
releases</a>.</em></p>
<blockquote>
<h2>v1.57.0</h2>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/temporalio/api-go/compare/v1.55.0...v1.57.0">https://github.com/temporalio/api-go/compare/v1.55.0...v1.57.0</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/temporalio/api-go/commit/c9e6db35e9dccf6549375c19c385255c311d32a6"><code>c9e6db3</code></a>
WorkerDeployments becoming async in nature. (<a
href="https://redirect.github.com/temporalio/api-go/issues/647">#647</a>)</li>
<li><a
href="https://github.com/temporalio/api-go/commit/fa3006123cf4e1409b9ba221ea6d6844570f848b"><code>fa30061</code></a>
Add identity to workflow update-options (<a
href="https://redirect.github.com/temporalio/api-go/issues/656">#656</a>)</li>
<li><a
href="https://github.com/temporalio/api-go/commit/d03ebc14064c2cfe879a793a51fd1606ca34d5b7"><code>d03ebc1</code></a>
Remove resource exhasted scopes for namespace shard and execution (<a
href="https://redirect.github.com/temporalio/api-go/issues/654">#654</a>)</li>
<li><a
href="https://github.com/temporalio/api-go/commit/49142121d692732c416611778e22d2670ea7ac5e"><code>4914212</code></a>
Revert &quot;serviceerror: add error checking helpers (<a
href="https://redirect.github.com/temporalio/api-go/issues/227">#227</a>)&quot;
(<a
href="https://redirect.github.com/temporalio/api-go/issues/228">#228</a>)</li>
<li><a
href="https://github.com/temporalio/api-go/commit/dc8b83b87ac71daec92e32d8f2d83c56362117e9"><code>dc8b83b</code></a>
Add per-namespace-per-shard scope in ResourceExhaustedScope (<a
href="https://redirect.github.com/temporalio/api-go/issues/649">#649</a>)</li>
<li><a
href="https://github.com/temporalio/api-go/commit/981440dcff4dc0dc67c77acc969f470538c02eaf"><code>981440d</code></a>
serviceerror: add error checking helpers (<a
href="https://redirect.github.com/temporalio/api-go/issues/227">#227</a>)</li>
<li>See full diff in <a
href="https://github.com/temporalio/api-go/compare/v1.55.0...v1.57.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=go.temporal.io/api&package-manager=go_modules&previous-version=1.55.0&new-version=1.57.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>