fix: multiple react versions in dev causes rules of hooks error (#745)
In development only, we receive the following error on the onboarding
route:

```
hook.js:608 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. overrideMethod @ hook.js:608 printWarning @ react.development.js:209 error @ react.development.js:183 resolveDispatcher @ react.development.js:1592 useLayoutEffect @ react.development.js:1641 In @ index.js:34 react_stack_bottom_frame @ react-dom-client.development.js:23863 renderWithHooks @ react-dom-client.development.js:5529 updateFunctionComponent @ react-dom-client.development.js:8897 beginWork @ react-dom-client.development.js:10522 runWithFiberInDEV @ react-dom-client.development.js:1519 performUnitOfWork @ react-dom-client.development.js:15132 workLoopSync @ react-dom-client.development.js:14956 renderRootSync @ react-dom-client.development.js:14936 performWorkOnRoot @ react-dom-client.development.js:14419 performSyncWorkOnRoot @ react-dom-client.development.js:16231 flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:16079 processRootScheduleInMicrotask @ react-dom-client.development.js:16116 (anonymous) @ react-dom-client.development.js:16250 <In> exports.jsxDEV @ react-jsx-dev-runtime.development.js:346 WebGLIn @ tunnel.tsx:9
```

This is because the `TextureLoader` component uses the `useVideoTexture`
hook from `@react-three/drei` which has a different version of React to
the main application. The docs mention this issue as a likely root
cause:
https://react.dev/warnings/invalid-hook-call-warning#duplicate-react

This doesn't happen in production, possibly due to StrictMode or Vite's
deduping (didn't confirm)